source 'https://rubygems.org'

# Specify your gem's dependencies in elasticsearch-model.gemspec
gemspec
gem 'appraisal'
gem 'elasticsearch-extensions', git: 'https://github.com/elastic/elasticsearch-ruby.git'