source 'https://rubygems.org'

gem 'rake'
gem 'ansi'

gem 'multi_json'
gem 'oj'
gem 'hashie'

gem 'patron'
gem 'elasticsearch'
gem 'elasticsearch-model',       path: File.expand_path('../../../../elasticsearch-model', __FILE__)
gem 'elasticsearch-persistence', path: File.expand_path('../../../', __FILE__)

gem 'sinatra', require: false
gem 'thin'

group :development do
  gem 'sinatra-contrib'
end

group :test do
  gem 'elasticsearch-extensions'
  gem 'rack-test'
  gem 'shoulda-context'
  gem 'turn'
  gem 'mocha'
end
