source 'https://rubygems.org'

gem 'rake'
gem 'ansi'

gem 'multi_json'
gem 'oj'
gem 'hashie'

gem 'patron'
gem 'elasticsearch'
gem 'elasticsearch-model',       git: 'https://github.com/elastic/elasticsearch-rails.git'
gem 'elasticsearch-persistence', git: 'https://github.com/elastic/elasticsearch-rails.git'

gem 'sinatra', require: false
gem 'thin'

group :development do
  gem 'sinatra-contrib'
end

group :test do
  gem 'elasticsearch-extensions'
  gem 'rack-test'
  gem 'shoulda-context'
  gem 'turn'
  gem 'mocha'
end
