# Licensed to Elasticsearch B.V. under one or more contributor
# license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright
# ownership. Elasticsearch B.V. licenses this file to you under
# the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

source 'https://rubygems.org'

# Specify your gem's dependencies in elasticsearch-rails.gemspec
gemspec

gem 'elasticsearch-model',
    path: File.expand_path('../elasticsearch-model', __dir__),
    require: false

gem 'elasticsearch-persistence',
    path: File.expand_path('../elasticsearch-persistence', __dir__),
    require: false

group :development, :testing do
  gem 'pry-nav'
  gem 'rspec'
  gem 'sqlite3' unless defined?(JRUBY_VERSION)
end
