source 'https://rubygems.org'

# Specify your gem's dependencies in elasticsearch-persistence.gemspec
gemspec

gem 'elasticsearch-model', :path => File.expand_path("../../elasticsearch-model", __FILE__), :require => false

gem 'virtus'
