require "bundler/gem_tasks"

desc "Run unit tests"
task :default => 'test:unit'
task :test    => 'test:unit'

# ----- Test tasks ------------------------------------------------------------

require 'rake/testtask'
require 'rspec/core/rake_task'

namespace :test do

  RSpec::Core::RakeTask.new(:spec)

  Rake::TestTask.new(:all) do |test|
    test.verbose = false
    test.warning = false
    test.deps = [ :spec ]
  end
end

namespace :bundle do
  desc 'Install gem dependencies'
  task :install do
    puts '-'*80
    Bundler.with_clean_env do
      sh 'bundle install'
    end
    puts '-'*80
  end
end

# ----- Documentation tasks ---------------------------------------------------

require 'yard'
YARD::Rake::YardocTask.new(:doc) do |t|
  t.options = %w| --embed-mixins --markup=markdown |
end

# ----- Code analysis tasks ---------------------------------------------------

if defined?(RUBY_VERSION) && RUBY_VERSION > '1.9'
  begin
    require 'cane/rake_task'
    Cane::RakeTask.new(:quality) do |cane|
      cane.abc_max = 15
      cane.style_measure = 120
    end
  rescue LoadError
    warn "cane not available, quality task not provided."
  end
end
