require "bundler/gem_tasks"

desc "Run unit tests"
task :default => 'test:unit'
task :test    => 'test:unit'

# ----- Test tasks ------------------------------------------------------------

require 'rake/testtask'
namespace :test do
  task :ci_reporter do
    ENV['CI_REPORTS'] ||= 'tmp/reports'
    require 'ci/reporter/rake/minitest'
    Rake::Task['ci:setup:minitest'].invoke
  end

  Rake::TestTask.new(:unit) do |test|
    Rake::Task['test:ci_reporter'].invoke if ENV['CI']
    test.libs << 'lib' << 'test'
    test.test_files = FileList["test/unit/**/*_test.rb"]
    test.verbose = false
    test.warning = false
  end

  Rake::TestTask.new(:integration) do |test|
    Rake::Task['test:ci_reporter'].invoke if ENV['CI']
    test.libs << 'lib' << 'test'
    test.test_files = FileList["test/integration/**/*_test.rb"]
    test.verbose = false
    test.warning = false
  end

  Rake::TestTask.new(:all) do |test|
    Rake::Task['test:ci_reporter'].invoke if ENV['CI']
    test.libs << 'lib' << 'test'
    test.test_files = FileList["test/unit/**/*_test.rb", "test/integration/**/*_test.rb"]
  end
end

# ----- Documentation tasks ---------------------------------------------------

require 'yard'
YARD::Rake::YardocTask.new(:doc) do |t|
  t.options = %w| --embed-mixins --markup=markdown |
end

# ----- Code analysis tasks ---------------------------------------------------

if defined?(RUBY_VERSION) && RUBY_VERSION > '1.9'
  begin
    require 'cane/rake_task'
    Cane::RakeTask.new(:quality) do |cane|
      cane.abc_max = 15
      cane.style_measure = 120
    end
  rescue LoadError
    warn "cane not available, quality task not provided."
  end
end
