name: JRuby tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    branches:
      - '*'
jobs:
  tests:
    env:
      TEST_ES_SERVER: http://localhost:9200
      RAILS_VERSIONS: ${{ matrix.rails }}
    strategy:
      fail-fast: false
      matrix:
        rails: [ '6.1', '7.0', '7.1' ]
        ruby: ['jruby-9.4']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Increase system limits
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144
    - uses: elastic/elastic-github-actions/elasticsearch@master
      with:
        stack-version: 8.15.0-SNAPSHOT
        security-enabled: false
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Bundle
      run: |
        sudo apt-get install libsqlite3-dev libcurl4-openssl-dev
        gem install bundler
        bundle install
        bundle exec rake bundle:clean
        bundle exec rake bundle:install
    - name: Test elasticsearch-rails
      run: cd elasticsearch-rails && bundle exec rake test:all
    - name: Test elasticsearch-persistence
      run: cd elasticsearch-persistence && bundle exec rake test:all
