name: JRuby
on:
  push:
    branches:
      - 7.x
  pull_request:
    branches:
      - 7.x
  workflow_dispatch:
    branches:
      - '*'
jobs:
  tests:
    env:
      TEST_ES_SERVER: http://localhost:9200
      RAILS_VERSIONS: '5.0,6.0'
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 'jruby-9.3', 'jruby-9.4' ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Increase system limits
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144
    - uses: elastic/elastic-github-actions/elasticsearch@master
      with:
        stack-version: 7.17-SNAPSHOT
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Bundle
      run: |
        gem install bundler
        bundle install
        bundle exec rake bundle:clean
        bundle exec rake bundle:install
    - name: Test elasticsearch-rails
      run: cd elasticsearch-rails && bundle exec rake test:all
    - name: Test elasticsearch-persistence
      run: cd elasticsearch-persistence && bundle exec rake test:all
