name: License headers
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3
    - name: Check license headers
      run: |
        ruby ./.github/check_license_headers.rb
